services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:${PORT:-8081}'
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
