// Datos de referencia extraídos de ComeYa_Base_Datos_Mercado_Puno_v4.xlsx (hojas 99_Listas, 11_Simulador_Pedido, 12_Resumen).
// Investigación de mercado para la ciudad de Puno, no precios verificados local por local.

// No hay fotos reales de cada plato; se usa un emoji representativo por categoría como presentación visual.
export const categoryEmoji: Record<string, string> = {
  'Caldos de mañana': '🍲',
  'Bebidas calientes': '☕',
  'Panes y sándwiches': '🥪',
  'Desayunos completos': '🍳',
  'Menú del día': '🍛',
  'Sopas': '🥣',
  'Segundos criollos': '🍖',
  'Regional puneño': '🫕',
  'Chifa': '🥡',
  'Pescados': '🐟',
  'Vegetariano': '🥗',
  'Acompañamientos': '🍚',
  'Pollo a la brasa': '🍗',
  'Broaster y frituras': '🍤',
  'Hamburguesas y sándwiches': '🍔',
  'Pizzas y pastas': '🍕',
  'Anticuchos y parrilla': '🍢',
  'Chifa nocturno': '🥡',
  'Caldos nocturnos': '🍲',
  'Cena ligera': '🥙',
  'Sushi y otros': '🍣',
  'Cuy': '🍖',
  'Carnes andinas': '🥩',
  'Platos de celebración': '🎉',
  'Truchas especiales': '🐟',
  'Menús especiales': '⭐',
  'Catering y volumen': '🍱',
  'Dietas especiales': '🥦',
  'Especial turístico': '🗺️',
  'Jugos naturales': '🧃',
  'Batidos y energizantes': '🥤',
  'Bebidas frías': '🧊',
  'Aperitivos y piqueos': '🍟',
  'Postres': '🍰',
  'Bebidas calientes de carretilla': '☕',
  'Jugos de carretilla': '🧃',
  'Panes y frituras de carretilla': '🥐',
  'Combos rápidos': '🍱',
  'Snacks de calle': '🌭',
  'Cerveza': '🍺',
  'Pisco y destilados nacionales': '🥃',
  'Ron y vodka': '🥃',
  'Whisky': '🥃',
  'Vinos': '🍷',
  'Licores y cremas': '🍸',
  'Combos y preparados': '🍹',
  'Complementos': '🧊',
};

export type CartaSummary = {
  key: string;
  label: string;
  products: number;
  avgPrice: number;
  minPrice: number;
  maxPrice: number;
  avgNet: number;
  avgCommission: number;
  schedule: string;
  scheduleNote: string;
  zoneContext: string;
};

// Fondo visual por carta para las tarjetas de producto (sin fotos reales disponibles, ver nota arriba).
export const cartaTheme: Record<string, string> = {
  'Desayunos': 'from-amber-100 via-orange-100 to-rose-100',
  'Almuerzos': 'from-yellow-100 via-amber-100 to-orange-100',
  'Cenas': 'from-orange-200 via-red-100 to-rose-200',
  'Especiales': 'from-fuchsia-100 via-purple-100 to-amber-100',
  'Jugos y aperitivos': 'from-lime-100 via-emerald-100 to-teal-100',
  'Jugos y desayuno rápido': 'from-sky-100 via-cyan-100 to-blue-100',
  'Licorería': 'from-amber-200 via-yellow-100 to-orange-200',
};

// Mapea cada subcategoría de producto (47) a su carta (7), según las hojas 01-07 del Excel.
export const categoryToCarta: Record<string, string> = {
  'Caldos de mañana': 'Desayunos',
  'Bebidas calientes': 'Desayunos',
  'Panes y sándwiches': 'Desayunos',
  'Desayunos completos': 'Desayunos',
  'Menú del día': 'Almuerzos',
  'Sopas': 'Almuerzos',
  'Segundos criollos': 'Almuerzos',
  'Regional puneño': 'Almuerzos',
  'Chifa': 'Almuerzos',
  'Pescados': 'Almuerzos',
  'Vegetariano': 'Almuerzos',
  'Acompañamientos': 'Almuerzos',
  'Pollo a la brasa': 'Cenas',
  'Broaster y frituras': 'Cenas',
  'Hamburguesas y sándwiches': 'Cenas',
  'Pizzas y pastas': 'Cenas',
  'Anticuchos y parrilla': 'Cenas',
  'Chifa nocturno': 'Cenas',
  'Caldos nocturnos': 'Cenas',
  'Cena ligera': 'Cenas',
  'Sushi y otros': 'Cenas',
  'Cuy': 'Especiales',
  'Carnes andinas': 'Especiales',
  'Platos de celebración': 'Especiales',
  'Truchas especiales': 'Especiales',
  'Menús especiales': 'Especiales',
  'Catering y volumen': 'Especiales',
  'Dietas especiales': 'Especiales',
  'Especial turístico': 'Especiales',
  'Jugos naturales': 'Jugos y aperitivos',
  'Batidos y energizantes': 'Jugos y aperitivos',
  'Bebidas frías': 'Jugos y aperitivos',
  'Aperitivos y piqueos': 'Jugos y aperitivos',
  'Postres': 'Jugos y aperitivos',
  'Bebidas calientes de carretilla': 'Jugos y desayuno rápido',
  'Jugos de carretilla': 'Jugos y desayuno rápido',
  'Panes y frituras de carretilla': 'Jugos y desayuno rápido',
  'Combos rápidos': 'Jugos y desayuno rápido',
  'Snacks de calle': 'Jugos y desayuno rápido',
  'Cerveza': 'Licorería',
  'Pisco y destilados nacionales': 'Licorería',
  'Ron y vodka': 'Licorería',
  'Whisky': 'Licorería',
  'Vinos': 'Licorería',
  'Licores y cremas': 'Licorería',
  'Combos y preparados': 'Licorería',
  'Complementos': 'Licorería',
};

export const cartaSummary: CartaSummary[] = [
  { key: 'desayunos', label: 'Desayunos', products: 92, avgPrice: 10.3, minPrice: 1, maxPrice: 70, avgNet: 9.43, avgCommission: 0.87, schedule: '05:00–11:00', scheduleNote: 'Calderías, cafeterías, desayunos completos', zoneContext: 'Puno está a más de 3,800 msnm a orillas del lago Titicaca; las madrugadas bajan cerca de 0 °C, por eso el desayuno gira en torno a caldos y bebidas calientes servidos desde las 5 a.m. en calderías y mercados como Laykakota y Bellavista.' },
  { key: 'almuerzos', label: 'Almuerzos', products: 171, avgPrice: 14.05, minPrice: 1, maxPrice: 56, avgNet: 12.76, avgCommission: 1.28, schedule: '11:00–16:00', scheduleNote: 'Menú del día, criollo, chifa, pescados del lago', zoneContext: 'El almuerzo es la comida fuerte del día puneño: picanterías y mercados sirven menú a precio fijo con pescado del Titicaca (pejerrey, trucha) y platos criollos, con mayor afluencia entre 12:00 y 14:00.' },
  { key: 'cenas', label: 'Cenas', products: 112, avgPrice: 21.9, minPrice: 4, maxPrice: 100, avgNet: 19.59, avgCommission: 2.31, schedule: '17:00–02:00', scheduleNote: 'Pollo a la brasa, broaster, chifa nocturno', zoneContext: 'Al caer la noche la temperatura baja rápido en el altiplano; pollerías, broasters y chifas alrededor de la avenida El Sol y el jirón Lima concentran la demanda de cena hasta la madrugada.' },
  { key: 'especiales', label: 'Especiales', products: 96, avgPrice: 111.34, minPrice: 5, maxPrice: 2000, avgNet: 97.19, avgCommission: 14.15, schedule: 'Bajo pedido', scheduleNote: 'Cuy, cancacho, pachamanca, catering: coordinar con anticipación', zoneContext: 'Puno es cuna de la Fiesta de la Candelaria y de celebraciones patronales todo el año; pachamancas, cancachos y cuy se piden con anticipación para reuniones familiares y fechas festivas en porciones grandes.' },
  { key: 'jugos-aperitivos', label: 'Jugos y aperitivos', products: 106, avgPrice: 8.22, minPrice: 1, maxPrice: 35, avgNet: 7.56, avgCommission: 0.66, schedule: '06:00–23:00', scheduleNote: 'Dos franjas: jugos por la mañana, piqueos y postres por la noche', zoneContext: 'Con sol fuerte de día y frío marcado de noche, el puneño alterna jugos de frutas frescas en la mañana con piqueos y postres para compartir al anochecer, junto a ferias y mercados de abasto.' },
  { key: 'jugos-rapido', label: 'Jugos y desayuno rápido', products: 98, avgPrice: 5.12, minPrice: 1, maxPrice: 18, avgNet: 4.75, avgCommission: 0.36, schedule: '05:00–09:00', scheduleNote: 'Carretillas y puestos de mercado: sin competencia formal en este horario', zoneContext: 'En paraderos y mercados de Puno, las carretillas atienden desde las 5 a.m. a trabajadores y transportistas con jugos y panes rápidos, un horario con poca oferta formal instalada.' },
  { key: 'licoreria', label: 'Licorería', products: 112, avgPrice: 46.22, minPrice: 3, maxPrice: 280, avgNet: 41.17, avgCommission: 5.05, schedule: '10:00–23:00', scheduleNote: 'Sujeto a ordenanza municipal vigente y verificación de mayoría de edad (Ley 28681)', zoneContext: 'Cerveza y pisco predominan en reuniones sociales y festividades puneñas; la venta está sujeta a ordenanza municipal vigente y a la verificación de mayoría de edad (Ley 28681).' },
];

export const cartaProductsTotal = cartaSummary.reduce((sum, carta) => sum + carta.products, 0);

// Librería local de fotos de producto: 186 archivos guardados en public/comeya-fotos/ del propio proyecto.
// Se descargaron de Wikimedia Commons (licencias libres para uso comercial: CC0, dominio público, CC-BY, CC-BY-SA)
// para no depender de enlaces externos. La atribución de cada archivo queda en categoryPhotoCredits.
// 3-4 fotos por categoría para que productos vecinos no repitan la misma imagen (ver pickCategoryPhoto).
export const categoryPhotos: Record<string, string[]> = {
  'Caldos de mañana': ['/comeya-fotos/caldos-de-manana-1.jpg', '/comeya-fotos/caldos-de-manana-2.jpg', '/comeya-fotos/caldos-de-manana-3.jpg', '/comeya-fotos/caldos-de-manana-4.jpg'],
  'Bebidas calientes': ['/comeya-fotos/bebidas-calientes-1.jpg', '/comeya-fotos/bebidas-calientes-2.jpg', '/comeya-fotos/bebidas-calientes-3.jpg', '/comeya-fotos/bebidas-calientes-4.jpg'],
  'Panes y sándwiches': ['/comeya-fotos/panes-y-sandwiches-1.jpg', '/comeya-fotos/panes-y-sandwiches-2.jpg', '/comeya-fotos/panes-y-sandwiches-3.jpg', '/comeya-fotos/panes-y-sandwiches-4.jpg'],
  'Desayunos completos': ['/comeya-fotos/desayunos-completos-1.jpg', '/comeya-fotos/desayunos-completos-2.jpg', '/comeya-fotos/desayunos-completos-3.jpg', '/comeya-fotos/desayunos-completos-4.jpg'],
  'Menú del día': ['/comeya-fotos/menu-del-dia-1.jpg', '/comeya-fotos/menu-del-dia-2.jpg', '/comeya-fotos/menu-del-dia-3.jpg', '/comeya-fotos/menu-del-dia-4.jpg'],
  'Sopas': ['/comeya-fotos/sopas-1.jpg', '/comeya-fotos/sopas-2.jpg', '/comeya-fotos/sopas-3.jpg', '/comeya-fotos/sopas-4.jpg'],
  'Segundos criollos': ['/comeya-fotos/segundos-criollos-1.jpg', '/comeya-fotos/segundos-criollos-2.jpg', '/comeya-fotos/segundos-criollos-3.jpg', '/comeya-fotos/segundos-criollos-4.jpg'],
  'Regional puneño': ['/comeya-fotos/regional-puneno-1.jpg', '/comeya-fotos/regional-puneno-2.jpg', '/comeya-fotos/regional-puneno-3.jpg', '/comeya-fotos/regional-puneno-4.jpg'],
  'Chifa': ['/comeya-fotos/chifa-1.jpg', '/comeya-fotos/chifa-2.jpg', '/comeya-fotos/chifa-3.jpg', '/comeya-fotos/chifa-4.jpg'],
  'Pescados': ['/comeya-fotos/pescados-1.jpg', '/comeya-fotos/pescados-2.jpg', '/comeya-fotos/pescados-3.jpg', '/comeya-fotos/pescados-4.jpg'],
  'Vegetariano': ['/comeya-fotos/vegetariano-1.png', '/comeya-fotos/vegetariano-2.jpg', '/comeya-fotos/vegetariano-3.jpg', '/comeya-fotos/vegetariano-4.jpg'],
  'Acompañamientos': ['/comeya-fotos/acompanamientos-1.jpg', '/comeya-fotos/acompanamientos-2.jpg', '/comeya-fotos/acompanamientos-3.jpg', '/comeya-fotos/acompanamientos-4.jpg'],
  'Pollo a la brasa': ['/comeya-fotos/pollo-a-la-brasa-1.jpg', '/comeya-fotos/pollo-a-la-brasa-2.jpg', '/comeya-fotos/pollo-a-la-brasa-3.jpg', '/comeya-fotos/pollo-a-la-brasa-4.jpg'],
  'Broaster y frituras': ['/comeya-fotos/broaster-y-frituras-1.jpg', '/comeya-fotos/broaster-y-frituras-2.jpg', '/comeya-fotos/broaster-y-frituras-3.jpg', '/comeya-fotos/broaster-y-frituras-4.jpg'],
  'Hamburguesas y sándwiches': ['/comeya-fotos/hamburguesas-y-sandwiches-1.jpg', '/comeya-fotos/hamburguesas-y-sandwiches-2.jpg', '/comeya-fotos/hamburguesas-y-sandwiches-3.jpg', '/comeya-fotos/hamburguesas-y-sandwiches-4.jpg'],
  'Pizzas y pastas': ['/comeya-fotos/pizzas-y-pastas-1.jpg', '/comeya-fotos/pizzas-y-pastas-2.jpg', '/comeya-fotos/pizzas-y-pastas-3.jpg', '/comeya-fotos/pizzas-y-pastas-4.jpg'],
  'Anticuchos y parrilla': ['/comeya-fotos/anticuchos-y-parrilla-1.jpg', '/comeya-fotos/anticuchos-y-parrilla-2.jpg', '/comeya-fotos/anticuchos-y-parrilla-3.jpg', '/comeya-fotos/anticuchos-y-parrilla-4.jpg'],
  'Chifa nocturno': ['/comeya-fotos/chifa-nocturno-1.jpg', '/comeya-fotos/chifa-nocturno-2.jpg', '/comeya-fotos/chifa-nocturno-3.jpg', '/comeya-fotos/chifa-nocturno-4.jpg'],
  'Caldos nocturnos': ['/comeya-fotos/caldos-nocturnos-1.jpg', '/comeya-fotos/caldos-nocturnos-2.jpg', '/comeya-fotos/caldos-nocturnos-3.jpg', '/comeya-fotos/caldos-nocturnos-4.jpg'],
  'Cena ligera': ['/comeya-fotos/cena-ligera-1.jpg', '/comeya-fotos/cena-ligera-2.jpg', '/comeya-fotos/cena-ligera-3.jpg', '/comeya-fotos/cena-ligera-4.jpg'],
  'Sushi y otros': ['/comeya-fotos/sushi-y-otros-1.jpg', '/comeya-fotos/sushi-y-otros-2.jpg', '/comeya-fotos/sushi-y-otros-3.jpg', '/comeya-fotos/sushi-y-otros-4.jpg'],
  'Cuy': ['/comeya-fotos/cuy-1.jpg', '/comeya-fotos/cuy-2.jpg', '/comeya-fotos/cuy-3.jpg', '/comeya-fotos/cuy-4.jpg'],
  'Carnes andinas': ['/comeya-fotos/carnes-andinas-1.jpg', '/comeya-fotos/carnes-andinas-2.jpg', '/comeya-fotos/carnes-andinas-3.jpg'],
  'Platos de celebración': ['/comeya-fotos/platos-de-celebracion-1.jpg', '/comeya-fotos/platos-de-celebracion-2.jpg', '/comeya-fotos/platos-de-celebracion-3.jpg', '/comeya-fotos/platos-de-celebracion-4.jpg'],
  'Truchas especiales': ['/comeya-fotos/truchas-especiales-1.jpg', '/comeya-fotos/truchas-especiales-2.jpg', '/comeya-fotos/truchas-especiales-3.jpg', '/comeya-fotos/truchas-especiales-4.jpg'],
  'Menús especiales': ['/comeya-fotos/menus-especiales-1.jpg', '/comeya-fotos/menus-especiales-2.jpg', '/comeya-fotos/menus-especiales-3.jpg', '/comeya-fotos/menus-especiales-4.jpg'],
  'Catering y volumen': ['/comeya-fotos/catering-y-volumen-1.jpg', '/comeya-fotos/catering-y-volumen-2.jpg', '/comeya-fotos/catering-y-volumen-3.jpg', '/comeya-fotos/catering-y-volumen-4.jpg'],
  'Dietas especiales': ['/comeya-fotos/dietas-especiales-1.jpg', '/comeya-fotos/dietas-especiales-2.jpg', '/comeya-fotos/dietas-especiales-3.jpg', '/comeya-fotos/dietas-especiales-4.jpg'],
  'Especial turístico': ['/comeya-fotos/especial-turistico-1.jpg', '/comeya-fotos/especial-turistico-2.jpg', '/comeya-fotos/especial-turistico-3.jpg', '/comeya-fotos/especial-turistico-4.jpg'],
  'Jugos naturales': ['/comeya-fotos/jugos-naturales-1.jpg', '/comeya-fotos/jugos-naturales-2.jpg', '/comeya-fotos/jugos-naturales-3.jpg', '/comeya-fotos/jugos-naturales-4.jpg'],
  'Batidos y energizantes': ['/comeya-fotos/batidos-y-energizantes-1.jpg', '/comeya-fotos/batidos-y-energizantes-2.jpg', '/comeya-fotos/batidos-y-energizantes-3.jpg', '/comeya-fotos/batidos-y-energizantes-4.jpg'],
  'Bebidas frías': ['/comeya-fotos/bebidas-frias-1.jpg', '/comeya-fotos/bebidas-frias-2.jpg', '/comeya-fotos/bebidas-frias-3.jpg', '/comeya-fotos/bebidas-frias-4.jpg'],
  'Aperitivos y piqueos': ['/comeya-fotos/aperitivos-y-piqueos-1.jpg', '/comeya-fotos/aperitivos-y-piqueos-2.jpg', '/comeya-fotos/aperitivos-y-piqueos-3.jpg', '/comeya-fotos/aperitivos-y-piqueos-4.jpg'],
  'Postres': ['/comeya-fotos/postres-1.jpg', '/comeya-fotos/postres-2.jpg', '/comeya-fotos/postres-3.jpg', '/comeya-fotos/postres-4.jpg'],
  'Bebidas calientes de carretilla': ['/comeya-fotos/bebidas-calientes-de-carretilla-1.jpg', '/comeya-fotos/bebidas-calientes-de-carretilla-2.jpg', '/comeya-fotos/bebidas-calientes-de-carretilla-3.jpg', '/comeya-fotos/bebidas-calientes-de-carretilla-4.jpg'],
  'Jugos de carretilla': ['/comeya-fotos/jugos-de-carretilla-1.jpg', '/comeya-fotos/jugos-de-carretilla-2.jpg', '/comeya-fotos/jugos-de-carretilla-3.jpg', '/comeya-fotos/jugos-de-carretilla-4.jpg'],
  'Panes y frituras de carretilla': ['/comeya-fotos/panes-y-frituras-de-carretilla-1.jpg', '/comeya-fotos/panes-y-frituras-de-carretilla-2.jpg', '/comeya-fotos/panes-y-frituras-de-carretilla-3.jpg', '/comeya-fotos/panes-y-frituras-de-carretilla-4.jpg'],
  'Combos rápidos': ['/comeya-fotos/combos-rapidos-1.jpg', '/comeya-fotos/combos-rapidos-2.jpg', '/comeya-fotos/combos-rapidos-3.jpg'],
  'Snacks de calle': ['/comeya-fotos/snacks-de-calle-1.jpg', '/comeya-fotos/snacks-de-calle-2.jpg', '/comeya-fotos/snacks-de-calle-3.jpg', '/comeya-fotos/snacks-de-calle-4.jpg'],
  'Cerveza': ['/comeya-fotos/cerveza-1.jpg', '/comeya-fotos/cerveza-2.jpg', '/comeya-fotos/cerveza-3.jpg', '/comeya-fotos/cerveza-4.jpg'],
  'Pisco y destilados nacionales': ['/comeya-fotos/pisco-y-destilados-nacionales-1.jpg', '/comeya-fotos/pisco-y-destilados-nacionales-2.jpg', '/comeya-fotos/pisco-y-destilados-nacionales-3.jpg', '/comeya-fotos/pisco-y-destilados-nacionales-4.jpg'],
  'Ron y vodka': ['/comeya-fotos/ron-y-vodka-1.jpg', '/comeya-fotos/ron-y-vodka-2.jpg', '/comeya-fotos/ron-y-vodka-3.jpg', '/comeya-fotos/ron-y-vodka-4.jpg'],
  'Whisky': ['/comeya-fotos/whisky-1.jpg', '/comeya-fotos/whisky-2.jpg', '/comeya-fotos/whisky-3.jpg', '/comeya-fotos/whisky-4.jpg'],
  'Vinos': ['/comeya-fotos/vinos-1.jpg', '/comeya-fotos/vinos-2.jpg', '/comeya-fotos/vinos-3.jpg', '/comeya-fotos/vinos-4.jpg'],
  'Licores y cremas': ['/comeya-fotos/licores-y-cremas-1.jpg', '/comeya-fotos/licores-y-cremas-2.jpg', '/comeya-fotos/licores-y-cremas-3.jpg', '/comeya-fotos/licores-y-cremas-4.jpg'],
  'Combos y preparados': ['/comeya-fotos/combos-y-preparados-1.jpg', '/comeya-fotos/combos-y-preparados-2.jpg', '/comeya-fotos/combos-y-preparados-3.jpg', '/comeya-fotos/combos-y-preparados-4.png'],
  'Complementos': ['/comeya-fotos/complementos-1.jpg', '/comeya-fotos/complementos-2.jpg', '/comeya-fotos/complementos-3.jpg', '/comeya-fotos/complementos-4.jpg'],
};

// Atribución por archivo local: archivo en la librería — origen en Wikimedia Commons — autor — licencia — ficha
export const categoryPhotoCredits: Record<string, Array<{ file: string; title: string; artist: string; license: string; sourceUrl: string }>> = {
  'Caldos de mañana': [{ file: 'caldos-de-manana-1.jpg', title: 'File:Chicken Noodle Soup US.jpg', artist: 'Nichijyou123', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Chicken_Noodle_Soup_US.jpg' }, { file: 'caldos-de-manana-2.jpg', title: 'File:Chicken Soup With Kreplach.jpg', artist: 'Yoninah', license: 'cc by 2.5', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Chicken_Soup_With_Kreplach.jpg' }, { file: 'caldos-de-manana-3.jpg', title: 'File:Liat Portal for Foodie Disorder - Chicken Soup with Rice Noodles.jpg', artist: 'HaJunkiyada', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Chicken_Soup_with_Rice_Noodles.jpg' }, { file: 'caldos-de-manana-4.jpg', title: 'File:Bowl of Vietnamese chicken soup with chili paste.jpg', artist: 'HungryHuy', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bowl_of_Vietnamese_chicken_soup_with_chili_paste.jpg' }],
  'Bebidas calientes': [{ file: 'bebidas-calientes-1.jpg', title: 'File:Coffee-cup-sleeve.jpg', artist: 'Nirzar', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Coffee-cup-sleeve.jpg' }, { file: 'bebidas-calientes-2.jpg', title: 'File:Cup of hot coffee.jpg', artist: 'Gabriel Fredrick Sindahnai', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cup_of_hot_coffee.jpg' }, { file: 'bebidas-calientes-3.jpg', title: 'File:Coffee cup lid.jpg', artist: 'Nirzar', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Coffee_cup_lid.jpg' }, { file: 'bebidas-calientes-4.jpg', title: 'File:Hot Coffee in the morning.jpg', artist: 'JBequio', license: 'cc by 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hot_Coffee_in_the_morning.jpg' }],
  'Panes y sándwiches': [{ file: 'panes-y-sandwiches-1.jpg', title: 'File:Sandwich bread (Bakers Choice).JPG', artist: 'Mk2010', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sandwich_bread_(Bakers_Choice).JPG' }, { file: 'panes-y-sandwiches-2.jpg', title: 'File:Peanut-Butter-Jelly-Sandwich.jpg', artist: 'Evan-Amos', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Peanut-Butter-Jelly-Sandwich.jpg' }, { file: 'panes-y-sandwiches-3.jpg', title: 'File:Sandwich on a cutting board.jpg', artist: 'Revital Salomon', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sandwich_on_a_cutting_board.jpg' }, { file: 'panes-y-sandwiches-4.jpg', title: 'File:White sandwich bread.jpg', artist: 'Wiki Farazi', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:White_sandwich_bread.jpg' }],
  'Desayunos completos': [{ file: 'desayunos-completos-1.jpg', title: 'File:Liat Portal for Foodie Disorder - Breakfast plate with sunny side egg and salad.jpg', artist: 'HaJunkiyada', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Breakfast_plate_with_sunny_side_egg_and_salad.jpg' }, { file: 'desayunos-completos-2.jpg', title: 'File:Liat Portal for Foodie Disorder - Breakfast in Israel scrambled eggs with herbs and vegetables.jpg', artist: 'HaJunkiyada', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Breakfast_in_Israel_scrambled_eggs_with_herbs_and_vegetables.jpg' }, { file: 'desayunos-completos-3.jpg', title: 'File:Liat Portal for Foodie Disorder - Israeli breakfast plate with egg, avocado, vegetables, and bread.jpg', artist: 'HaJunkiyada', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Israeli_breakfast_plate_with_egg,_avocado,_vegetables,_and_bread.jpg' }, { file: 'desayunos-completos-4.jpg', title: 'File:Liat Portal for Foodie Disorder - Israeli breakfast plate with fried egg and avocado.jpg', artist: 'HaJunkiyada', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Israeli_breakfast_plate_with_fried_egg_and_avocado.jpg' }],
  'Menú del día': [{ file: 'menu-del-dia-1.jpg', title: 'File:Arroz con pollo en buffet (cropped).jpg', artist: 'Samuel Renard from Brest, France', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Arroz_con_pollo_en_buffet_(cropped).jpg' }, { file: 'menu-del-dia-2.jpg', title: 'File:Arroz con pollo peruano.jpg', artist: 'MiguelAlanCS', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Arroz_con_pollo_peruano.jpg' }, { file: 'menu-del-dia-3.jpg', title: 'File:Arroz con pollo y papa a la huancaina.JPG', artist: 'Dtarazona', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Arroz_con_pollo_y_papa_a_la_huancaina.JPG' }, { file: 'menu-del-dia-4.jpg', title: 'File:PERU GASTRONOMIA.jpg', artist: 'Sonia Macedo', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:PERU_GASTRONOMIA.jpg' }],
  'Sopas': [{ file: 'sopas-1.jpg', title: 'File:Traditional Vegetable Soup from Argentina.jpg', artist: 'Horacio Cambeiro', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Traditional_Vegetable_Soup_from_Argentina.jpg' }, { file: 'sopas-2.jpg', title: 'File:-2022-02-01 Bowl of spring vegetable soup, Trimingham, Norfolk.JPG', artist: 'Kolforn (Kolforn) I\'d appreciate if you could mail me (Kolforn@gmai...', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:-2022-02-01_Bowl_of_spring_vegetable_soup,_Trimingham,_Norfolk.JPG' }, { file: 'sopas-3.jpg', title: 'File:Liat Portal for Foodie Disorder - Vegetable Soup with Chicken Dumplings.jpg', artist: 'HaJunkiyada', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Vegetable_Soup_with_Chicken_Dumplings.jpg' }, { file: 'sopas-4.jpg', title: 'File:Vegetable soup and bread at the office.jpg', artist: 'JIP', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vegetable_soup_and_bread_at_the_office.jpg' }],
  'Segundos criollos': [{ file: 'segundos-criollos-1.jpg', title: 'File:Lomo-saltado-perudelights.jpg', artist: 'WikiHes', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Lomo-saltado-perudelights.jpg' }, { file: 'segundos-criollos-2.jpg', title: 'File:Lomo saltado El Fogon Huaraz 19122009.JPG', artist: 'Dtarazona', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Lomo_saltado_El_Fogon_Huaraz_19122009.JPG' }, { file: 'segundos-criollos-3.jpg', title: 'File:Lomo Salteado.jpg', artist: 'PapiPijuan', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Lomo_Salteado.jpg' }, { file: 'segundos-criollos-4.jpg', title: 'File:Lomo saltado peruano.jpg', artist: 'Miguel Alan Córdova Silva', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Lomo_saltado_peruano.jpg' }],
  'Regional puneño': [{ file: 'regional-puneno-1.jpg', title: 'File:Fried trout Trucha frita con papas y arroz (31008005061).jpg', artist: 'Lucerito Corrales from Lima, Perú', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fried_trout_Trucha_frita_con_papas_y_arroz_(31008005061).jpg' }, { file: 'regional-puneno-2.jpg', title: 'File:Trucha frita con vista al puerto de Copacabana.jpg', artist: 'Mferjh', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Trucha_frita_con_vista_al_puerto_de_Copacabana.jpg' }, { file: 'regional-puneno-3.jpg', title: 'File:Trucha frita.jpg', artist: 'Abelchristian111', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Trucha_frita.jpg' }, { file: 'regional-puneno-4.jpg', title: 'File:TruchaFrita.jpg', artist: 'Akizia', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:TruchaFrita.jpg' }],
  'Chifa': [{ file: 'chifa-1.jpg', title: 'File:Arroz chaufa simple.JPG', artist: 'Dtarazona', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Arroz_chaufa_simple.JPG' }, { file: 'chifa-2.jpg', title: 'File:Arroz Chaufa preparation.jpg', artist: 'MOs810', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Arroz_Chaufa_preparation.jpg' }, { file: 'chifa-3.jpg', title: 'File:Arroz chaufa especial 12032009.JPG', artist: 'Dtarazona', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Arroz_chaufa_especial_12032009.JPG' }, { file: 'chifa-4.jpg', title: 'File:Arroz Chaufa Especial (410312809).jpg', artist: 'Luis Tamayo from Dallas, Texas, USA, USA', license: 'cc by-sa 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Arroz_Chaufa_Especial_(410312809).jpg' }],
  'Pescados': [{ file: 'pescados-1.jpg', title: 'File:Seafood in Spain - Gran Canaria grilled fish and seafood plate.jpg', artist: 'Marek Ślusarczyk (Tupungato) Photo portfolio', license: 'cc by 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Seafood_in_Spain_-_Gran_Canaria_grilled_fish_and_seafood_plate.jpg' }, { file: 'pescados-2.jpg', title: 'File:02 Grilled fish and seafood dinner in Canary Islands - Gran Canaria restaurant, marisco mixto a la parrilla.jpg', artist: 'Marek Ślusarczyk (Tupungato) Photo portfolio', license: 'cc by 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:02_Grilled_fish_and_seafood_dinner_in_Canary_Islands_-_Gran_Canaria_restaurant,_marisco_mixto_a_la_parrilla.jpg' }, { file: 'pescados-3.jpg', title: 'File:Grilled fish, Lazaru\'s Restaurant, New Urbane Hotel, 2025 (01).jpg', artist: 'Bahnfrend', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Grilled_fish,_Lazaru%27s_Restaurant,_New_Urbane_Hotel,_2025_(01).jpg' }, { file: 'pescados-4.jpg', title: 'File:01 Food in Gran Canaria - fish and seafood mixed grill plate.jpg', artist: 'Marek Ślusarczyk (Tupungato) Photo portfolio', license: 'cc by 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:01_Food_in_Gran_Canaria_-_fish_and_seafood_mixed_grill_plate.jpg' }],
  'Vegetariano': [{ file: 'vegetariano-1.png', title: 'File:Homemade Argentine Russian Salad (Ensalada Rusa).png', artist: 'Horacio Cambeiro', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Homemade_Argentine_Russian_Salad_(Ensalada_Rusa).png' }, { file: 'vegetariano-2.jpg', title: 'File:Salads and drinks in Iydea.jpg', artist: 'Andy Li', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Salads_and_drinks_in_Iydea.jpg' }, { file: 'vegetariano-3.jpg', title: 'File:Liat Portal for Foodie Disorder - Homemade Pea Soup with Salad.jpg', artist: 'HaJunkiyada', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Homemade_Pea_Soup_with_Salad.jpg' }, { file: 'vegetariano-4.jpg', title: 'File:Healthy quinoa salad with dried fruit.jpg', artist: 'TorbeyCharbel', license: 'cc by 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Healthy_quinoa_salad_with_dried_fruit.jpg' }],
  'Acompañamientos': [{ file: 'acompanamientos-1.jpg', title: 'File:Milanesa plated with lemon slices and french fries (in Buenos Aires, Argentina).jpg', artist: 'Ben Tavener', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Milanesa_plated_with_lemon_slices_and_french_fries_(in_Buenos_Aires,_Argentina).jpg' }, { file: 'acompanamientos-2.jpg', title: 'File:Homemade hamburgers and french fries from Argentina.jpg', artist: 'Horacio Cambeiro', license: 'cc by 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Homemade_hamburgers_and_french_fries_from_Argentina.jpg' }, { file: 'acompanamientos-3.jpg', title: 'File:Argentine-style French fries served with mozzarella pizza.jpg', artist: 'Horacio Cambeiro', license: 'cc by 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Argentine-style_French_fries_served_with_mozzarella_pizza.jpg' }, { file: 'acompanamientos-4.jpg', title: 'File:Fried egg surrounded by French fries on a white plate.jpg', artist: 'Horacio Cambeiro', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fried_egg_surrounded_by_French_fries_on_a_white_plate.jpg' }],
  'Pollo a la brasa': [{ file: 'pollo-a-la-brasa-1.jpg', title: 'File:Pollo a la brasa pierna con papas.JPG', artist: 'Dtarazona', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pollo_a_la_brasa_pierna_con_papas.JPG' }, { file: 'pollo-a-la-brasa-2.jpg', title: 'File:Pollo a la brasa - 29837174642.jpg', artist: 'tacowitte', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pollo_a_la_brasa_-_29837174642.jpg' }, { file: 'pollo-a-la-brasa-3.jpg', title: 'File:Pollo a la brasa para llevar.JPG', artist: 'Marcomogollon', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pollo_a_la_brasa_para_llevar.JPG' }, { file: 'pollo-a-la-brasa-4.jpg', title: 'File:Pollo a la brasa peruano.jpg', artist: 'Manuel González Olaechea', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pollo_a_la_brasa_peruano.jpg' }],
  'Broaster y frituras': [{ file: 'broaster-y-frituras-1.jpg', title: 'File:Fried chicken Burger in Milan, Italy.jpg', artist: 'Pava', license: 'cc by-sa 3.0 it', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fried_chicken_Burger_in_Milan,_Italy.jpg' }, { file: 'broaster-y-frituras-2.jpg', title: 'File:Fried chicken legs, Rostov-on-Don, Russia.jpg', artist: 'Vyacheslav Argenberg', license: 'cc by 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fried_chicken_legs,_Rostov-on-Don,_Russia.jpg' }, { file: 'broaster-y-frituras-3.jpg', title: 'File:Fried Chicken and Donut.jpg', artist: 'ZhengZhou', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fried_Chicken_and_Donut.jpg' }, { file: 'broaster-y-frituras-4.jpg', title: 'File:Fried rice with chicken (17234644521).jpg', artist: 'Vee Satayamas from Bangkok, Thailand', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fried_rice_with_chicken_(17234644521).jpg' }],
  'Hamburguesas y sándwiches': [{ file: 'hamburguesas-y-sandwiches-1.jpg', title: 'File:Big Mac hamburger.jpg', artist: 'Evan-Amos', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Big_Mac_hamburger.jpg' }, { file: 'hamburguesas-y-sandwiches-2.jpg', title: 'File:NCI Visuals Food Hamburger.jpg', artist: 'Len Rizzi (photographer)', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:NCI_Visuals_Food_Hamburger.jpg' }, { file: 'hamburguesas-y-sandwiches-3.jpg', title: 'File:Burger King double cheeseburger.jpg', artist: 'Luke', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Burger_King_double_cheeseburger.jpg' }, { file: 'hamburguesas-y-sandwiches-4.jpg', title: 'File:Cultivated hamburger, 2013.jpg', artist: 'Mosa Meat', license: 'cc by 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cultivated_hamburger,_2013.jpg' }],
  'Pizzas y pastas': [{ file: 'pizzas-y-pastas-1.jpg', title: 'File:Vegetarian Pizza.jpg', artist: 'Petar Milošević', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vegetarian_Pizza.jpg' }, { file: 'pizzas-y-pastas-2.jpg', title: 'File:Eq it-na pizza-margherita sep2005 sml.jpg', artist: 'Valerio Capello at English Wikipedia', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Eq_it-na_pizza-margherita_sep2005_sml.jpg' }, { file: 'pizzas-y-pastas-3.jpg', title: 'File:L&B Spumoni Gardens pizza (41436).jpg', artist: 'Rhododendrites', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:L%26B_Spumoni_Gardens_pizza_(41436).jpg' }, { file: 'pizzas-y-pastas-4.jpg', title: 'File:Pizza 2023.jpg', artist: 'Yakshitha', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pizza_2023.jpg' }],
  'Anticuchos y parrilla': [{ file: 'anticuchos-y-parrilla-1.jpg', title: 'File:Anticucho del Perú.JPG', artist: 'No machine-readable author provided. Manuel González Olaechea assum...', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Anticucho_del_Per%C3%BA.JPG' }, { file: 'anticuchos-y-parrilla-2.jpg', title: 'File:Anticuchos on a skewer, Raices Peruvian Cuisine.jpg', artist: 'Ser Amantio di Nicolao', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Anticuchos_on_a_skewer,_Raices_Peruvian_Cuisine.jpg' }, { file: 'anticuchos-y-parrilla-3.jpg', title: 'File:Sliced-up anticuchos on a plate.jpg', artist: 'Ser Amantio di Nicolao', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sliced-up_anticuchos_on_a_plate.jpg' }, { file: 'anticuchos-y-parrilla-4.jpg', title: 'File:Anticuchos! Independence Day (Peru).jpg', artist: 'Suedehead', license: 'cc by-sa 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Anticuchos!_Independence_Day_(Peru).jpg' }],
  'Chifa nocturno': [{ file: 'chifa-nocturno-1.jpg', title: 'File:Chinese fried rice.jpg', artist: 'Archon6812', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Chinese_fried_rice.jpg' }, { file: 'chifa-nocturno-2.jpg', title: 'File:Chinese egg fried rice.jpg', artist: 'Euniceyeoh07', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Chinese_egg_fried_rice.jpg' }, { file: 'chifa-nocturno-3.jpg', title: 'File:Mini abalones fried rice with choi sum.jpg', artist: 'Peachyeung316', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mini_abalones_fried_rice_with_choi_sum.jpg' }, { file: 'chifa-nocturno-4.jpg', title: 'File:King prawns fried rice, Stir Fry by CK.jpg', artist: 'Andy Li', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:King_prawns_fried_rice,_Stir_Fry_by_CK.jpg' }],
  'Caldos nocturnos': [{ file: 'caldos-nocturnos-1.jpg', title: 'File:House Special (Beef) - The Big Bowl.jpg', artist: 'Andy Li', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:House_Special_(Beef)_-_The_Big_Bowl.jpg' }, { file: 'caldos-nocturnos-2.jpg', title: 'File:Song dynasty\'s \'Patriotic soup\' -Protect the Country Dish (護國菜) .jpg', artist: 'NeoBatfreak', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Song_dynasty%27s_%27Patriotic_soup%27_-Protect_the_Country_Dish_(%E8%AD%B7%E5%9C%8B%E8%8F%9C)_.jpg' }, { file: 'caldos-nocturnos-3.jpg', title: 'File:Bowl of menudo stew.jpg', artist: 'David Martin Davies', license: 'cc by-sa 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bowl_of_menudo_stew.jpg' }, { file: 'caldos-nocturnos-4.jpg', title: 'File:Song dynasty\'s \'patriotic soup\' (prepared in Clovis California) 宋朝的“護國菜”（在加利福尼亞克洛維斯市製備）。.jpg', artist: 'NeoBatfreak', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Song_dynasty%27s_%27patriotic_soup%27_(prepared_in_Clovis_California)_%E5%AE%8B%E6%9C%9D%E7%9A%84%E2%80%9C%E8%AD%B7%E5%9C%8B%E8%8F%9C%E2%80%9D%EF%BC%88%E5%9C%A8%E5%8A%A0%E5%88%A9%E7%A6%8F%E5%B0%BC%E4%BA%9E%E5%85%8B%E6%B4%9B%E7%B6%AD%E6%96%AF%E5%B8%82%E8%A3%BD%E5%82%99%EF%BC%89%E3%80%82.jpg' }],
  'Cena ligera': [{ file: 'cena-ligera-1.jpg', title: 'File:Liat Portal for Foodie Disorder - Israeli avocado salad dinner.jpg', artist: 'HaJunkiyada', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Israeli_avocado_salad_dinner.jpg' }, { file: 'cena-ligera-2.jpg', title: 'File:Avocado-pecan salad.jpg', artist: 'FranHogan', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Avocado-pecan_salad.jpg' }, { file: 'cena-ligera-3.jpg', title: 'File:Avocado Mango Salad.jpg', artist: 'Shark2025', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Avocado_Mango_Salad.jpg' }, { file: 'cena-ligera-4.jpg', title: 'File:Liat Portal for Foodie Disorder - Open turkey sandwich with avocado salad and pickles.jpg', artist: 'HaJunkiyada', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Open_turkey_sandwich_with_avocado_salad_and_pickles.jpg' }],
  'Sushi y otros': [{ file: 'sushi-y-otros-1.jpg', title: 'File:Sushi and Sashimi.jpg', artist: 'ActivBowser9177', license: 'cc by 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sushi_and_Sashimi.jpg' }, { file: 'sushi-y-otros-2.jpg', title: 'File:Sushi rolls placed on their display stand.jpg', artist: 'Jameswasswa', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sushi_rolls_placed_on_their_display_stand.jpg' }, { file: 'sushi-y-otros-3.jpg', title: 'File:Sushi rolls on a table with other foods.jpg', artist: 'Jameswasswa', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sushi_rolls_on_a_table_with_other_foods.jpg' }, { file: 'sushi-y-otros-4.jpg', title: 'File:Sushi Rolls - plated - 洪洪烧腊 (885698278).jpg', artist: 'Alpha from Melbourne, Australia', license: 'cc by-sa 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sushi_Rolls_-_plated_-_%E6%B4%AA%E6%B4%AA%E7%83%A7%E8%85%8A_(885698278).jpg' }],
  'Cuy': [{ file: 'cuy-1.jpg', title: 'File:Cuy chactao.jpg', artist: 'Jorge Gobbi', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cuy_chactao.jpg' }, { file: 'cuy-2.jpg', title: 'File:Cuy Chactado.jpg', artist: 'MovEditor', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cuy_Chactado.jpg' }, { file: 'cuy-3.jpg', title: 'File:Plato de Cuy - 1.jpg', artist: 'Marostegui', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Plato_de_Cuy_-_1.jpg' }, { file: 'cuy-4.jpg', title: 'File:Plato de cuy.JPG', artist: 'Jharni Elmer Neyra Valverde', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Plato_de_cuy.JPG' }],
  'Carnes andinas': [{ file: 'carnes-andinas-1.jpg', title: 'File:Lunch with Alpaca steak - Hiram Bingham train by Perurail to Machu Picchu and Sacred Valley Peru (4875591227).jpg', artist: 'David Berkowitz from New York, NY, USA', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Lunch_with_Alpaca_steak_-_Hiram_Bingham_train_by_Perurail_to_Machu_Picchu_and_Sacred_Valley_Peru_(4875591227).jpg' }, { file: 'carnes-andinas-2.jpg', title: 'File:Carne de alpaca.jpg', artist: 'Roger Otoni', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Carne_de_alpaca.jpg' }, { file: 'carnes-andinas-3.jpg', title: 'File:Alpaca blanca.jpg', artist: 'BERNARDO VALENTIN', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Alpaca_blanca.jpg' }],
  'Platos de celebración': [{ file: 'platos-de-celebracion-1.jpg', title: 'File:Pachamanca Peru.JPG', artist: 'Javi270270', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pachamanca_Peru.JPG' }, { file: 'platos-de-celebracion-2.jpg', title: 'File:Pachamanca in Peru.jpg', artist: 'Unukorno', license: 'cc by 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pachamanca_in_Peru.jpg' }, { file: 'platos-de-celebracion-3.jpg', title: 'File:Pachamanca de cerdo.jpg', artist: 'Jilmer Atanacio Inocente', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pachamanca_de_cerdo.jpg' }, { file: 'platos-de-celebracion-4.jpg', title: 'File:Pachamanca 4.jpg', artist: 'ErikaGuetti', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pachamanca_4.jpg' }],
  'Truchas especiales': [{ file: 'truchas-especiales-1.jpg', title: 'File:TruchaFrita.jpg', artist: 'Akizia', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:TruchaFrita.jpg' }, { file: 'truchas-especiales-2.jpg', title: 'File:Trucha frita con vista al puerto de Copacabana.jpg', artist: 'Mferjh', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Trucha_frita_con_vista_al_puerto_de_Copacabana.jpg' }, { file: 'truchas-especiales-3.jpg', title: 'File:Fried trout Trucha frita con papas y arroz (31008005061).jpg', artist: 'Lucerito Corrales from Lima, Perú', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fried_trout_Trucha_frita_con_papas_y_arroz_(31008005061).jpg' }, { file: 'truchas-especiales-4.jpg', title: 'File:Trucha frita.jpg', artist: 'Abelchristian111', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Trucha_frita.jpg' }],
  'Menús especiales': [{ file: 'menus-especiales-1.jpg', title: 'File:Plate of food at Maurice\'s Gourmet BBQ.jpg', artist: 'Nathan Cardozo', license: 'cc by-sa 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Plate_of_food_at_Maurice%27s_Gourmet_BBQ.jpg' }, { file: 'menus-especiales-2.jpg', title: 'File:Comida gourmet Méxicana.jpg', artist: 'TitaMey53', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Comida_gourmet_M%C3%A9xicana.jpg' }, { file: 'menus-especiales-3.jpg', title: 'File:\'Gourmet cheeseburger\' - Bradleys Original Tea Hut at High Beach, Essex, England 1.jpg', artist: 'Acabashi', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:%27Gourmet_cheeseburger%27_-_Bradleys_Original_Tea_Hut_at_High_Beach,_Essex,_England_1.jpg' }, { file: 'menus-especiales-4.jpg', title: 'File:Comida gourmet Méxicana 2.jpg', artist: 'TitaMey53', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Comida_gourmet_M%C3%A9xicana_2.jpg' }],
  'Catering y volumen': [{ file: 'catering-y-volumen-1.jpg', title: 'File:Waterfall buffet table.jpg', artist: 'Ɱ', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Waterfall_buffet_table.jpg' }, { file: 'catering-y-volumen-2.jpg', title: 'File:Sideboard and sarcophagus.jpg', artist: 'Unknown authorUnknown author', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sideboard_and_sarcophagus.jpg' }, { file: 'catering-y-volumen-3.jpg', title: 'File:ATC Buffet Table 1.jpg', artist: 'Narek75', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:ATC_Buffet_Table_1.jpg' }, { file: 'catering-y-volumen-4.jpg', title: 'File:Buffet table at the Wikimania 2013 welcome party at Sky100 - 20130808.jpg', artist: 'Stephan Schulz', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Buffet_table_at_the_Wikimania_2013_welcome_party_at_Sky100_-_20130808.jpg' }],
  'Dietas especiales': [{ file: 'dietas-especiales-1.jpg', title: 'File:Healthy salad bowl (42231145040).jpg', artist: 'Ella Olsson from Stockholm, Sweden', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Healthy_salad_bowl_(42231145040).jpg' }, { file: 'dietas-especiales-2.jpg', title: 'File:Healthy quinoa salad with dried fruit.jpg', artist: 'TorbeyCharbel', license: 'cc by 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Healthy_quinoa_salad_with_dried_fruit.jpg' }, { file: 'dietas-especiales-3.jpg', title: 'File:Healthy Lentil Salad (Unsplash).jpg', artist: 'James Sutton jamessutton_photography', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Healthy_Lentil_Salad_(Unsplash).jpg' }, { file: 'dietas-especiales-4.jpg', title: 'File:Healthy meal prep with fresh salad, fruits, and planning tools displayed on a table.jpg', artist: 'Shixart1985', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Healthy_meal_prep_with_fresh_salad,_fruits,_and_planning_tools_displayed_on_a_table.jpg' }],
  'Especial turístico': [{ file: 'especial-turistico-1.jpg', title: 'File:Timbuche, comida tipica.jpg', artist: 'Raninbima05', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Timbuche,_comida_tipica.jpg' }, { file: 'especial-turistico-2.jpg', title: 'File:Almuerzo con comida de la selva.jpg', artist: 'Jorge Gobbi from Buenos Aires, Argentina', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Almuerzo_con_comida_de_la_selva.jpg' }, { file: 'especial-turistico-3.jpg', title: 'File:Ispi Paceño.jpg', artist: 'Miika Fernández', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ispi_Pace%C3%B1o.jpg' }, { file: 'especial-turistico-4.jpg', title: 'File:Combinacion lomo saltado.jpg', artist: 'Jorge Gobbi from Buenos Aires, Argentina', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Combinacion_lomo_saltado.jpg' }],
  'Jugos naturales': [{ file: 'jugos-naturales-1.jpg', title: 'File:Fresh fruit and juice preparation on a sunny kitchen countertop with vibrant colors and healthful options.jpg', artist: 'Shixart1985', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fresh_fruit_and_juice_preparation_on_a_sunny_kitchen_countertop_with_vibrant_colors_and_healthful_options.jpg' }, { file: 'jugos-naturales-2.jpg', title: 'File:Enjoying fresh oranges and juice on a sunny morning.jpg', artist: 'Shixart1985', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Enjoying_fresh_oranges_and_juice_on_a_sunny_morning.jpg' }, { file: 'jugos-naturales-3.jpg', title: 'File:Woman writing notes while enjoying a fresh fruit platter and juice.jpg', artist: 'Shixart1985', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Woman_writing_notes_while_enjoying_a_fresh_fruit_platter_and_juice.jpg' }, { file: 'jugos-naturales-4.jpg', title: 'File:Woman writing notes while enjoying juice at a bright kitchen table surrounded by fresh fruits.jpg', artist: 'Shixart1985', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Woman_writing_notes_while_enjoying_juice_at_a_bright_kitchen_table_surrounded_by_fresh_fruits.jpg' }],
  'Batidos y energizantes': [{ file: 'batidos-y-energizantes-1.jpg', title: 'File:Fresh fruit smoothie being poured into a glass.jpg', artist: 'Shixart1985', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fresh_fruit_smoothie_being_poured_into_a_glass.jpg' }, { file: 'batidos-y-energizantes-2.jpg', title: 'File:Fresh fruit smoothie preparation with assorted fruits on a table.jpg', artist: 'Shixart1985', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fresh_fruit_smoothie_preparation_with_assorted_fruits_on_a_table.jpg' }, { file: 'batidos-y-energizantes-3.jpg', title: 'File:Glass of strawberry smoothie (6828826294).jpg', artist: 'woodleywonderworks', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Glass_of_strawberry_smoothie_(6828826294).jpg' }, { file: 'batidos-y-energizantes-4.jpg', title: 'File:Woman writing notes while enjoying a fresh fruit platter and juice.jpg', artist: 'Shixart1985', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Woman_writing_notes_while_enjoying_a_fresh_fruit_platter_and_juice.jpg' }],
  'Bebidas frías': [{ file: 'bebidas-frias-1.jpg', title: 'File:Glass of Iced Syrup.jpg', artist: 'Yohanadisetiawanbjn', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Glass_of_Iced_Syrup.jpg' }, { file: 'bebidas-frias-2.jpg', title: 'File:HK 旺角 Mongkok 始創中心 Pioneer Centre exhibition Oct 2017 IX1 tableware glass iced drink cups.jpg', artist: 'Bowarsiuc', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:HK_%E6%97%BA%E8%A7%92_Mongkok_%E5%A7%8B%E5%89%B5%E4%B8%AD%E5%BF%83_Pioneer_Centre_exhibition_Oct_2017_IX1_tableware_glass_iced_drink_cups.jpg' }, { file: 'bebidas-frias-3.jpg', title: 'File:HK 旺角 Mongkok 始創中心 Pioneer Centre exhibition Oct 2017 IX1 Warning sign Slippy floor n iced drink glass cup.jpg', artist: 'Bowarsiuc', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:HK_%E6%97%BA%E8%A7%92_Mongkok_%E5%A7%8B%E5%89%B5%E4%B8%AD%E5%BF%83_Pioneer_Centre_exhibition_Oct_2017_IX1_Warning_sign_Slippy_floor_n_iced_drink_glass_cup.jpg' }, { file: 'bebidas-frias-4.jpg', title: 'File:Glass of Cola.jpg', artist: 'Cocktailmarler', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Glass_of_Cola.jpg' }],
  'Aperitivos y piqueos': [{ file: 'aperitivos-y-piqueos-1.jpg', title: 'File:Ceviche de pescado (La Punta, Callao).jpg', artist: 'Jorge G. Mori', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ceviche_de_pescado_(La_Punta,_Callao).jpg' }, { file: 'aperitivos-y-piqueos-2.jpg', title: 'File:Ceviche del Perú.jpg', artist: 'No machine-readable author provided. Manuel González Olaechea assum...', license: 'cc by 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ceviche_del_Per%C3%BA.jpg' }, { file: 'aperitivos-y-piqueos-3.jpg', title: 'File:Ceviche 01211.jpg', artist: 'Waterloo1883', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ceviche_01211.jpg' }, { file: 'aperitivos-y-piqueos-4.jpg', title: 'File:Ceviche peruano es inscrita en la Lista Representativa de Patrimonio Cultural Inmaterial de la Humanidad - 53381967964.jpg', artist: 'MINISTERIO DE LA PRODUCCIÓN - PRODUCE', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ceviche_peruano_es_inscrita_en_la_Lista_Representativa_de_Patrimonio_Cultural_Inmaterial_de_la_Humanidad_-_53381967964.jpg' }],
  'Postres': [{ file: 'postres-1.jpg', title: 'File:Piece of chocolate cake on a white plate decorated with chocolate sauce.jpg', artist: 'Daria YakovlevaMinor edits made by Subsidiary account', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Piece_of_chocolate_cake_on_a_white_plate_decorated_with_chocolate_sauce.jpg' }, { file: 'postres-2.jpg', title: 'File:Chocolate Hedgehog Slice @ Mount Pleasant Bakery & Cafe 20250111-131250.jpg', artist: 'RegionVisitor90', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Chocolate_Hedgehog_Slice_@_Mount_Pleasant_Bakery_%26_Cafe_20250111-131250.jpg' }, { file: 'postres-3.jpg', title: 'File:Slice of Heaven Desserts on Display At Ferguson Plarre\'s Bakehouse of Southland.jpg', artist: 'Brassluff', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Slice_of_Heaven_Desserts_on_Display_At_Ferguson_Plarre%27s_Bakehouse_of_Southland.jpg' }, { file: 'postres-4.jpg', title: 'File:Hedgehog Slice 20240730-135857.jpg', artist: 'RegionVisitor90', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hedgehog_Slice_20240730-135857.jpg' }],
  'Bebidas calientes de carretilla': [{ file: 'bebidas-calientes-de-carretilla-1.jpg', title: 'File:Emol.jpg', artist: 'MiguelAlanCS', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Emol.jpg' }, { file: 'bebidas-calientes-de-carretilla-2.jpg', title: 'File:Vendedora de emoliente.jpg', artist: 'Abelchristian111', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vendedora_de_emoliente.jpg' }, { file: 'bebidas-calientes-de-carretilla-3.jpg', title: 'File:PRODUCE y la Municipalidad de Independencia celebraron el Día del Emoliente - 54340629468.jpg', artist: 'MINISTERIO DE LA PRODUCCIÓN - PRODUCE', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:PRODUCE_y_la_Municipalidad_de_Independencia_celebraron_el_D%C3%ADa_del_Emoliente_-_54340629468.jpg' }, { file: 'bebidas-calientes-de-carretilla-4.jpg', title: 'File:PRODUCE y la Municipalidad de Independencia celebraron el Día del Emoliente - 54340825970.jpg', artist: 'MINISTERIO DE LA PRODUCCIÓN - PRODUCE', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:PRODUCE_y_la_Municipalidad_de_Independencia_celebraron_el_D%C3%ADa_del_Emoliente_-_54340825970.jpg' }],
  'Jugos de carretilla': [{ file: 'jugos-de-carretilla-1.jpg', title: 'File:Cane juice stand Hyderabad 2006.jpg', artist: 'Linda N.', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cane_juice_stand_Hyderabad_2006.jpg' }, { file: 'jugos-de-carretilla-2.jpg', title: 'File:Juice Stand in Herzl Street P1080363.JPG', artist: 'Deror Avi', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Juice_Stand_in_Herzl_Street_P1080363.JPG' }, { file: 'jugos-de-carretilla-3.jpg', title: 'File:Juice Stand in Herzl Street P1080364.JPG', artist: 'Deror Avi', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Juice_Stand_in_Herzl_Street_P1080364.JPG' }, { file: 'jugos-de-carretilla-4.jpg', title: 'File:Juice stand In Ameerpet Hyderabad.jpg', artist: 'ShashiBellamkonda', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Juice_stand_In_Ameerpet_Hyderabad.jpg' }],
  'Panes y frituras de carretilla': [{ file: 'panes-y-frituras-de-carretilla-1.jpg', title: 'File:Balık-ekmek in Ankara.jpg', artist: 'E4024', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bal%C4%B1k-ekmek_in_Ankara.jpg' }, { file: 'panes-y-frituras-de-carretilla-2.jpg', title: 'File:Frankfurt am Main, Balık-ekmek boat (Meral Imbiss).jpg', artist: 'Dr. Thomas Liptak', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Frankfurt_am_Main,_Bal%C4%B1k-ekmek_boat_(Meral_Imbiss).jpg' }, { file: 'panes-y-frituras-de-carretilla-3.jpg', title: 'File:Fried bread Burma.jpg', artist: '咽頭べさ', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fried_bread_Burma.jpg' }, { file: 'panes-y-frituras-de-carretilla-4.jpg', title: 'File:Balık Ekmek stand.jpg', artist: 'PapaYoung89', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bal%C4%B1k_Ekmek_stand.jpg' }],
  'Combos rápidos': [{ file: 'combos-rapidos-1.jpg', title: 'File:Burger King Whopper Combo.jpg', artist: 'user Siqbal', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Burger_King_Whopper_Combo.jpg' }, { file: 'combos-rapidos-2.jpg', title: 'File:Breakfast Plater - Hotel Central Plaza. Siliguri - West Bengal - DSC 002.jpg', artist: 'Xylem7', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Breakfast_Plater_-_Hotel_Central_Plaza._Siliguri_-_West_Bengal_-_DSC_002.jpg' }, { file: 'combos-rapidos-3.jpg', title: 'File:The Giant hamburger, fries and soda - Quick.jpg', artist: 'L. W. Yang', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:The_Giant_hamburger,_fries_and_soda_-_Quick.jpg' }],
  'Snacks de calle': [{ file: 'snacks-de-calle-1.jpg', title: 'File:Punugulu1.JPG', artist: 'Balajijagadesh', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Punugulu1.JPG' }, { file: 'snacks-de-calle-2.jpg', title: 'File:كناكر (Kanāker, Syrian snack).jpg', artist: 'El Mono Español', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:%D9%83%D9%86%D8%A7%D9%83%D8%B1_(Kan%C4%81ker,_Syrian_snack).jpg' }, { file: 'snacks-de-calle-3.jpg', title: 'File:SZ Shenzhen 零食有鳴 Yummy Snack Food night September 2026 N13P 01.jpg', artist: 'HUTSEUM ChamZ', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:SZ_Shenzhen_%E9%9B%B6%E9%A3%9F%E6%9C%89%E9%B3%B4_Yummy_Snack_Food_night_September_2026_N13P_01.jpg' }, { file: 'snacks-de-calle-4.jpg', title: 'File:Burmese snack street vendor in Yangon.jpg', artist: 'ta@keshi kimi', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Burmese_snack_street_vendor_in_Yangon.jpg' }],
  'Cerveza': [{ file: 'cerveza-1.jpg', title: 'File:Beer wuerzburger hofbraue v.jpg', artist: 'Christian "VisualBeo" Horvat', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Beer_wuerzburger_hofbraue_v.jpg' }, { file: 'cerveza-2.jpg', title: 'File:Beer bottles 2018 G1.jpg', artist: 'George Chernilevsky', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Beer_bottles_2018_G1.jpg' }, { file: 'cerveza-3.jpg', title: 'File:Lav beer and glass - 2012-10-12 - Andy Mabbett.jpg', artist: 'Andy Mabbett', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Lav_beer_and_glass_-_2012-10-12_-_Andy_Mabbett.jpg' }, { file: 'cerveza-4.jpg', title: 'File:Beer and pizza on display in a restaurant on a rustic table with focus on the glass of beer.jpg', artist: 'Nenad Stojkovic', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Beer_and_pizza_on_display_in_a_restaurant_on_a_rustic_table_with_focus_on_the_glass_of_beer.jpg' }],
  'Pisco y destilados nacionales': [{ file: 'pisco-y-destilados-nacionales-1.jpg', title: 'File:Pisco sour 20100613b.JPG', artist: 'Dtarazona', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pisco_sour_20100613b.JPG' }, { file: 'pisco-y-destilados-nacionales-2.jpg', title: 'File:Pisco sour (buffet).JPG', artist: 'Dtarazona', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pisco_sour_(buffet).JPG' }, { file: 'pisco-y-destilados-nacionales-3.jpg', title: 'File:Pisco Sour 2.jpg', artist: 'Erich Wagner (www.eventografie.de)', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pisco_Sour_2.jpg' }, { file: 'pisco-y-destilados-nacionales-4.jpg', title: 'File:Pisco Sour Cocktail.jpg', artist: 'Bart Everson', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Pisco_Sour_Cocktail.jpg' }],
  'Ron y vodka': [{ file: 'ron-y-vodka-1.jpg', title: 'File:Stroh Inländer Rum 80 bottle rear.jpg', artist: 'Alex P. Kok', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Stroh_Inl%C3%A4nder_Rum_80_bottle_rear.jpg' }, { file: 'ron-y-vodka-2.jpg', title: 'File:Stroh Inländer Rum 80 bottle.jpg', artist: 'Alex P. Kok', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Stroh_Inl%C3%A4nder_Rum_80_bottle.jpg' }, { file: 'ron-y-vodka-3.jpg', title: 'File:Frederick Judd Waugh Rum Row 1922.jpg', artist: 'Frederick Judd Waugh', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Frederick_Judd_Waugh_Rum_Row_1922.jpg' }, { file: 'ron-y-vodka-4.jpg', title: 'File:Bottle and glass.jpg', artist: 'Michael2134094', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Bottle_and_glass.jpg' }],
  'Whisky': [{ file: 'whisky-1.jpg', title: 'File:Glencairn Whisky Glass...jpg', artist: 'Amiko82', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Glencairn_Whisky_Glass...jpg' }, { file: 'whisky-2.jpg', title: 'File:Glencairn Glass-pjt.jpg', artist: 'Pjt56', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Glencairn_Glass-pjt.jpg' }, { file: 'whisky-3.jpg', title: 'File:Glencairn whisky glass and lights.jpg', artist: 'Trogain', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Glencairn_whisky_glass_and_lights.jpg' }, { file: 'whisky-4.jpg', title: 'File:Whisky glass.jpg', artist: 'Petar Milošević', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Whisky_glass.jpg' }],
  'Vinos': [{ file: 'vinos-1.jpg', title: 'File:Wine being poured into a glass.jpg', artist: 'Fabio Ingrosso', license: 'cc by 2.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Wine_being_poured_into_a_glass.jpg' }, { file: 'vinos-2.jpg', title: 'File:Red and white wine in glass.jpg', artist: 'André Karwath', license: 'cc by-sa 2.5', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Red_and_white_wine_in_glass.jpg' }, { file: 'vinos-3.jpg', title: 'File:020260524 140002 Red wine in glass.jpg', artist: 'Auctor quaerendae', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:020260524_140002_Red_wine_in_glass.jpg' }, { file: 'vinos-4.jpg', title: 'File:Copas de cristal de Baccarat de principios del siglo XX red wine glass.jpg', artist: 'Pillolino77', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Copas_de_cristal_de_Baccarat_de_principios_del_siglo_XX_red_wine_glass.jpg' }],
  'Licores y cremas': [{ file: 'licores-y-cremas-1.jpg', title: 'File:Liqueur Glass (France), 1893 (CH 51685091).jpg', artist: 'Unknown artistUnknown artist', license: 'public domain', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liqueur_Glass_(France),_1893_(CH_51685091).jpg' }, { file: 'licores-y-cremas-2.jpg', title: 'File:Liqueur glass MET 264492.jpg', artist: 'Wikimedia Commons', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liqueur_glass_MET_264492.jpg' }, { file: 'licores-y-cremas-3.jpg', title: 'File:Liqueur glass MET 264492 1975.1.1152.jpg', artist: 'Wikimedia Commons', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liqueur_glass_MET_264492_1975.1.1152.jpg' }, { file: 'licores-y-cremas-4.jpg', title: 'File:Liqueur glass MET 69747.jpg', artist: 'Wikimedia Commons', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liqueur_glass_MET_69747.jpg' }],
  'Combos y preparados': [{ file: 'combos-y-preparados-1.jpg', title: 'File:15-09-26-RalfR-WLC-0059.jpg', artist: 'Ralf Roletschek', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:15-09-26-RalfR-WLC-0059.jpg' }, { file: 'combos-y-preparados-2.jpg', title: 'File:15-09-26-RalfR-WLC-0056.jpg', artist: 'Ralf Roletschek', license: 'cc by-sa 3.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:15-09-26-RalfR-WLC-0056.jpg' }, { file: 'combos-y-preparados-3.jpg', title: 'File:Cocktail L.jpg', artist: 'Il Tuchino', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Cocktail_L.jpg' }, { file: 'combos-y-preparados-4.png', title: 'File:Mixed Drinks Barnstar.png', artist: 'Jerium', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mixed_Drinks_Barnstar.png' }],
  'Complementos': [{ file: 'complementos-1.jpg', title: 'File:Liat Portal for Foodie Disorder - Mixed nuts and dried fruit.jpg', artist: 'HaJunkiyada', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Mixed_nuts_and_dried_fruit.jpg' }, { file: 'complementos-2.jpg', title: 'File:Liat Portal for Foodie Disorder - Pear, nuts, and blue cheese healthy bowl.jpg', artist: 'HaJunkiyada', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Pear,_nuts,_and_blue_cheese_healthy_bowl.jpg' }, { file: 'complementos-3.jpg', title: 'File:Liat Portal for Foodie Disorder - Mixed nuts and dried cranberries.jpg', artist: 'HaJunkiyada', license: 'cc by-sa 4.0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Mixed_nuts_and_dried_cranberries.jpg' }, { file: 'complementos-4.jpg', title: 'File:Nuts-484262.jpg', artist: 'Trostle', license: 'cc0', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Nuts-484262.jpg' }],
};

export const photoLibraryTotal = 186;

export type CommissionSegment = { segment: string; pct: number };

export const commissionSegments: CommissionSegment[] = [
  { segment: 'Económico', pct: 0.07 },
  { segment: 'Estándar', pct: 0.09 },
  { segment: 'Medio', pct: 0.11 },
  { segment: 'Premium', pct: 0.13 },
];

export type DeliveryZone = { zone: string; fee: number };

export const deliveryZones: DeliveryZone[] = [
  { zone: 'Centro / Plaza de Armas', fee: 3 },
  { zone: 'Mercado Central / Jr. Oquendo', fee: 3 },
  { zone: 'Barrio Bellavista', fee: 4 },
  { zone: 'Barrio Huáscar', fee: 4 },
  { zone: 'Av. El Sol', fee: 3.5 },
  { zone: 'Av. La Torre', fee: 3.5 },
  { zone: 'Av. Simón Bolívar', fee: 4 },
  { zone: 'Av. Circunvalación', fee: 4.5 },
  { zone: 'Av. Sesquicentenario', fee: 4 },
  { zone: 'Chanu Chanu', fee: 4.5 },
  { zone: 'Salcedo', fee: 5 },
  { zone: 'Alto Puno', fee: 6 },
  { zone: 'Jayllihuaya', fee: 6.5 },
  { zone: 'Taparachi / periferia', fee: 6.5 },
  { zone: 'Puerto / Uros', fee: 5 },
];

export type ComboIdea = { name: string; carta: string; category: string; price: number };

export const comboIdeas: ComboIdea[] = [
  { name: 'Combo desayuno para 2', carta: 'Desayunos', category: 'Desayunos completos', price: 29 },
  { name: 'Combo familiar pollo + gaseosa', carta: 'Cenas', category: 'Pollo a la brasa', price: 70 },
  { name: 'Combo alitas + papas + gaseosa', carta: 'Cenas', category: 'Broaster y frituras', price: 27.5 },
  { name: 'Combo hamburguesa + papas + gaseosa', carta: 'Cenas', category: 'Hamburguesas y sándwiches', price: 19.5 },
  { name: 'Combo pizza familiar + gaseosa 1.5 L', carta: 'Cenas', category: 'Pizzas y pastas', price: 54 },
  { name: 'Combo oficina (jugo + sándwich + fruta)', carta: 'Jugos y desayuno rápido', category: 'Combos rápidos', price: 11.5 },
];

export const orderSimulatorDefaults = {
  productPrice: 10,
  packagingCost: 1,
  commissionPct: 0.07,
  deliveryFee: 4,
  courierPay: 3.5,
  serviceFee: 0.5,
  gatewayPct: 0.04,
  gatewayFixed: 0,
  monthlyFixedCosts: 3000,
};

export type TopConsumedItem = { name: string; category: string; note: string };

// Top 3 por carta: productos marcados como ancla o de mayor rotación en la observación comercial del Excel; se completa hasta 3 con productos de la misma categoría.
export const topConsumedByCarta: Record<string, TopConsumedItem[]> = {
  'Desayunos': [
    { name: 'Caldo de gallina', category: 'Caldos de mañana', note: 'Producto rey del desayuno puneño; se vende desde la madrugada' },
    { name: 'Caldo de cabeza', category: 'Caldos de mañana', note: 'Muy pedido los fines de semana' },
    { name: 'Mate de coca', category: 'Bebidas calientes', note: 'Muy pedido por turistas' },
  ],
  'Almuerzos': [
    { name: 'Menú económico completo', category: 'Menú del día', note: 'PRODUCTO ANCLA de ComeYa' },
    { name: 'Arroz a la cubana', category: 'Segundos criollos', note: 'Plato de mayor rotación en menú popular' },
    { name: 'Lomo saltado', category: 'Segundos criollos', note: 'Plato de mayor rotación a la carta' },
  ],
  'Cenas': [
    { name: '1/4 de pollo a la brasa', category: 'Pollo a la brasa', note: 'Producto de mayor rotación en la noche' },
    { name: 'Mostrito', category: 'Broaster y frituras', note: 'Muy pedido por público joven' },
    { name: 'Combo 1/4 + gaseosa personal', category: 'Pollo a la brasa', note: 'Combo de mayor rotación' },
  ],
  'Especiales': [
    { name: 'Cuy chactado', category: 'Cuy', note: 'Requiere pedido anticipado; avisar 1 hora antes' },
    { name: 'Cuy al horno', category: 'Cuy', note: '' },
    { name: 'Cuy broaster', category: 'Cuy', note: '' },
  ],
  'Jugos y aperitivos': [
    { name: 'Jugo de papaya', category: 'Jugos naturales', note: 'Mercado Central concentra juguerías' },
    { name: 'Jugo de piña', category: 'Jugos naturales', note: '' },
    { name: 'Jugo de naranja', category: 'Jugos naturales', note: '' },
  ],
  'Jugos y desayuno rápido': [
    { name: 'Api + pan con chicharrón', category: 'Combos rápidos', note: 'COMBO ANCLA de la lista: sube el ticket de S/ 3 a S/ 8' },
    { name: 'Api con buñuelo', category: 'Bebidas calientes de carretilla', note: 'Clásico de la mañana fría puneña; el vaso debe ir sellado' },
    { name: 'Api solo', category: 'Bebidas calientes de carretilla', note: '' },
  ],
  'Licorería': [
    { name: 'Combo cuba libre (ron + gaseosa + hielo)', category: 'Combos y preparados', note: 'Muy pedido en la noche' },
    { name: 'Vino caliente / navegado', category: 'Vinos', note: 'Muy pedido en noches frías de Puno' },
    { name: 'Cerveza Cusqueña 620 ml', category: 'Cerveza', note: 'Marca de mayor presencia en el sur' },
  ],
};
