// Padrón de locales de Puno extraído de la hoja 08_Restaurantes de ComeYa_Base_Datos_Mercado_Puno_v5_2.xlsx.
// Sesgo conocido del padrón público: se concentra en el centro turístico; los menús de barrio y las carretillas
// se levantan en campo, por eso teléfono, horario, menú diario y prioridad llegan vacíos y se completan desde el formulario.

export type ComeyaRestaurant = {
  name: string;
  localType: string;
  cuisine: string;
  address: string;
  zone: string;
  segment: string;
  cartas: string;
  dailyMenu: string;
  menuPrice: string;
  cartaRange: string;
  phone: string;
  schedule: string;
  ownDelivery: string;
  platform: string;
  priority: string;
  source: string;
  lat?: number;
  lng?: number;
};

export const restaurantDirectory: ComeyaRestaurant[] = [
  { name: 'Mojsa Restaurante', localType: 'Restaurante turístico', cuisine: 'Novoandina / peruana', address: 'Jr. Lima 635, 2do piso', zone: 'Centro / Plaza de Armas', segment: 'Medio', cartas: 'Almuerzos, Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público (Wanderlog / Avalos Tours)' },
  { name: 'La Casona Restaurant', localType: 'Restaurante turístico', cuisine: 'Parrilla / pizzería / andina', address: 'Jr. Lima 423', zone: 'Centro / Plaza de Armas', segment: 'Medio', cartas: 'Almuerzos, Cenas, Especiales', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público; aliado de PideloPuno' },
  { name: 'Tulipans Restaurant', localType: 'Restaurante turístico', cuisine: 'Internacional / pizzas', address: 'Jr. Lima 394', zone: 'Centro / Plaza de Armas', segment: 'Medio', cartas: 'Almuerzos, Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'Balcones de Puno', localType: 'Restaurante turístico', cuisine: 'Peruana / show folclórico', address: 'Jr. Libertad 354', zone: 'Centro / Plaza de Armas', segment: 'Medio', cartas: 'Cenas, Especiales', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'La Estancia Grill', localType: 'Parrilla', cuisine: 'Carnes a la parrilla', address: 'Jr. Libertad 137', zone: 'Centro / Plaza de Armas', segment: 'Medio', cartas: 'Cenas, Especiales', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'Alma Bar Restaurante', localType: 'Restaurante turístico', cuisine: 'Peruana contemporánea', address: 'Av. Sesquicentenario 1970', zone: 'Av. Sesquicentenario', segment: 'Premium', cartas: 'Cenas, Especiales', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'La Table del\' Inca', localType: 'Restaurante turístico', cuisine: 'Fusión franco-peruana', address: 'Jr. Ancash 239', zone: 'Centro / Plaza de Armas', segment: 'Premium', cartas: 'Cenas, Especiales', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público (Avalos Tours)' },
  { name: 'Café Bar Casa del Corregidor', localType: 'Cafetería', cuisine: 'Café / carta ligera', address: 'Jr. Deustua 576', zone: 'Centro / Plaza de Armas', segment: 'Estándar', cartas: 'Desayunos, Jugos y aperitivos', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'Loving Hut Puno', localType: 'Vegetariano / vegano', cuisine: 'Vegana', address: 'Choque Huanca 188', zone: 'Centro / Plaza de Armas', segment: 'Estándar', cartas: 'Almuerzos, Especiales', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público — referente vegano local' },
  { name: 'Incabar', localType: 'Cafetería', cuisine: 'Café / bar / desayunos', address: 'Jr. Lima 653', zone: 'Centro / Plaza de Armas', segment: 'Estándar', cartas: 'Desayunos, Jugos y aperitivos', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'RUPHA', localType: 'Cafetería', cuisine: 'Café / bistró', address: 'Jr. Moquegua 338', zone: 'Centro / Plaza de Armas', segment: 'Estándar', cartas: 'Desayunos, Almuerzos', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'Giorgio Restaurant', localType: 'Restaurante turístico', cuisine: 'Peruana / internacional', address: 'Jr. Lima 430', zone: 'Centro / Plaza de Armas', segment: 'Medio', cartas: 'Almuerzos, Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'Colors', localType: 'Restaurante turístico', cuisine: 'Fusión internacional', address: 'Jr. Lima 342', zone: 'Centro / Plaza de Armas', segment: 'Medio', cartas: 'Almuerzos, Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'VALERIA Restaurant', localType: 'Restaurante turístico', cuisine: 'Peruana / latina', address: 'Jr. Lima 369', zone: 'Centro / Plaza de Armas', segment: 'Medio', cartas: 'Almuerzos, Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'Machupizza', localType: 'Pizzería', cuisine: 'Pizzas', address: 'Centro de Puno', zone: 'Centro / Plaza de Armas', segment: 'Estándar', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'Sushi Ten Bento', localType: 'Japonés / fusión', cuisine: 'Japonesa', address: 'Jr. Ancash 239', zone: 'Centro / Plaza de Armas', segment: 'Medio', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'Casa Grill Puno', localType: 'Parrilla', cuisine: 'Parrillas', address: 'Jr. Moquegua 318', zone: 'Centro / Plaza de Armas', segment: 'Medio', cartas: 'Cenas, Especiales', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'Pacha Restaurante & Draft Bar', localType: 'Restaurante turístico', cuisine: 'Peruana / bar', address: 'Jr. Grau 338', zone: 'Centro / Plaza de Armas', segment: 'Medio', cartas: 'Cenas, Jugos y aperitivos', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'Plaza Oriental Restaurant', localType: 'Chifa', cuisine: 'China', address: 'Jr. Lima', zone: 'Centro / Plaza de Armas', segment: 'Estándar', cartas: 'Almuerzos, Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'Las Cantutas del Lago', localType: 'Restaurante turístico', cuisine: 'Novoandina', address: 'Jr. Joaquín Inclán', zone: 'Centro / Plaza de Armas', segment: 'Medio', cartas: 'Almuerzos, Especiales', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público' },
  { name: 'Los Uros', localType: 'Restaurante turístico', cuisine: 'Peruana', address: 'Isla Esteves, lago Titicaca', zone: 'Puerto / Uros', segment: 'Premium', cartas: 'Almuerzos, Especiales', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público — fuera del radio urbano' },
  { name: 'Chifa Cheng Xin', localType: 'Chifa', cuisine: 'Chifa', address: 'Puno', zone: 'Por confirmar', segment: 'Estándar', cartas: 'Almuerzos, Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público; figuraba en Nora Delivery' },
  { name: 'Chifa Jin Cheng Jiu Jia', localType: 'Chifa', cuisine: 'Chifa', address: 'Puno', zone: 'Por confirmar', segment: 'Estándar', cartas: 'Almuerzos, Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público (Carta.menu)' },
  { name: 'Chifa Nan Hua', localType: 'Chifa', cuisine: 'Chifa', address: 'Puno', zone: 'Por confirmar', segment: 'Estándar', cartas: 'Almuerzos, Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio público (Carta.menu)' },
  { name: 'Chifa Cuatro Dragones', localType: 'Chifa', cuisine: 'Chifa', address: 'Puno', zone: 'Por confirmar', segment: 'Estándar', cartas: 'Almuerzos, Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Aliado actual de PideloPuno' },
  { name: 'Chifa Mr. Dragon', localType: 'Chifa', cuisine: 'Chifa', address: 'Puno', zone: 'Por confirmar', segment: 'Estándar', cartas: 'Almuerzos, Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Aliado actual de PideloPuno' },
  { name: 'Pollería El Rancho', localType: 'Pollería', cuisine: 'Pollo a la brasa', address: 'Jr. Oquendo 210 / Miguel Urbina 115', zone: 'Centro / Plaza de Armas', segment: 'Estándar', cartas: 'Cenas, Especiales', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio iPerú — tel. 947730043' },
  { name: 'Pollería El Rico Riko', localType: 'Pollería', cuisine: 'Pollo a la brasa', address: 'Av. La Torre 341', zone: 'Av. La Torre', segment: 'Estándar', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio iPerú — tel. (051) 351064' },
  { name: 'Pollería El Parador', localType: 'Pollería', cuisine: 'Pollo a la brasa', address: 'Av. El Sol 1270', zone: 'Av. El Sol', segment: 'Estándar', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio iPerú' },
  { name: 'La Choza de Óscar', localType: 'Pollería', cuisine: 'Pollo a la brasa', address: 'Jr. Libertad 354', zone: 'Centro / Plaza de Armas', segment: 'Estándar', cartas: 'Cenas, Especiales', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio iPerú — tel. (051) 351199; aliado de PideloPuno' },
  { name: 'Pollería Rico Ricón', localType: 'Pollería', cuisine: 'Pollo a la brasa', address: 'Av. Simón Bolívar 1015', zone: 'Av. Simón Bolívar', segment: 'Estándar', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio iPerú' },
  { name: 'Pollería Piolín', localType: 'Pollería', cuisine: 'Pollo a la brasa', address: 'Av. Circunvalación 1711', zone: 'Av. Circunvalación', segment: 'Estándar', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio iPerú' },
  { name: 'Pollería Pollo Gamonal', localType: 'Pollería', cuisine: 'Pollo a la brasa', address: 'Av. Sesquicentenario 123', zone: 'Av. Sesquicentenario', segment: 'Estándar', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio iPerú' },
  { name: 'Pollería Pinos Brass', localType: 'Pollería', cuisine: 'Pollo a la brasa', address: 'Puno', zone: 'Por confirmar', segment: 'Estándar', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Reseñado en Tripadvisor' },
  { name: 'Pollería Las Palmeras', localType: 'Pollería', cuisine: 'Pollo a la brasa', address: 'Puno', zone: 'Por confirmar', segment: 'Estándar', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Directorio Planeta Perú' },
  { name: 'Broastería Doña Ysabel', localType: 'Broastería / salchipapería', cuisine: 'Broaster y salchipapa', address: 'Puno', zone: 'Por confirmar', segment: 'Económico', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Aliado actual de PideloPuno' },
  { name: 'Sabor Peruano', localType: 'Broastería / salchipapería', cuisine: 'Broaster y salchipapa', address: 'Puno', zone: 'Por confirmar', segment: 'Económico', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Aliado actual de PideloPuno' },
  { name: 'Pizzería Remix', localType: 'Pizzería', cuisine: 'Pizzas', address: 'Puno', zone: 'Por confirmar', segment: 'Estándar', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Aliado actual de PideloPuno' },
  { name: 'Sr. Pizza', localType: 'Pizzería', cuisine: 'Pizzas', address: 'Puno', zone: 'Por confirmar', segment: 'Estándar', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Aliado actual de PideloPuno' },
  { name: 'Pizzería Oasis', localType: 'Pizzería', cuisine: 'Pizzas', address: 'Puno', zone: 'Por confirmar', segment: 'Estándar', cartas: 'Cenas', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Aliado actual de PideloPuno' },
  { name: 'Cevichería Muelle Sur', localType: 'Cevichería', cuisine: 'Pescados y mariscos', address: 'Puno', zone: 'Por confirmar', segment: 'Medio', cartas: 'Almuerzos, Especiales', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Aliado actual de PideloPuno' },
  { name: 'Cevichería Costa Brava', localType: 'Cevichería', cuisine: 'Pescados y mariscos', address: 'Puno', zone: 'Por confirmar', segment: 'Medio', cartas: 'Almuerzos', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Aliado actual de PideloPuno' },
  { name: 'Cevichería Rico Pez', localType: 'Cevichería', cuisine: 'Pescados y mariscos', address: 'Puno', zone: 'Por confirmar', segment: 'Estándar', cartas: 'Almuerzos', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Aliado actual de PideloPuno' },
  { name: 'La Provincial', localType: 'Menú popular', cuisine: 'Comida criolla', address: 'Puno', zone: 'Por confirmar', segment: 'Estándar', cartas: 'Almuerzos', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Aliado actual de PideloPuno' },
  { name: 'Mercado Central de Puno', localType: 'Puesto de mercado', cuisine: 'Desayunos, caldos, jugos, comida típica', address: 'Jr. Oquendo / Jr. Arequipa', zone: 'Mercado Central / Jr. Oquendo', segment: 'Económico', cartas: 'Desayunos, Almuerzos, Jugos y aperitivos, Jugos y desayuno rápido', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Verificado — concentra calderías y juguerías. PUNTO CLAVE para desayunos: levantar puesto por puesto' },
  { name: 'Mercado Bellavista', localType: 'Puesto de mercado', cuisine: 'Comida popular y jugos', address: 'Barrio Bellavista', zone: 'Barrio Bellavista', segment: 'Económico', cartas: 'Desayunos, Almuerzos, Jugos y desayuno rápido', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Alto tráfico — levantar puesto por puesto' },
  { name: 'Mercado Laykakota', localType: 'Puesto de mercado', cuisine: 'Menú popular y jugos', address: 'Zona Laykakota', zone: 'Av. El Sol', segment: 'Económico', cartas: 'Almuerzos, Jugos y desayuno rápido', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Zona de menús de S/ 8 a S/ 10 referida por el usuario — verificar en campo' },
  { name: 'Carretillas Plaza de Armas / Jr. Lima', localType: 'Carretilla / ambulante', cuisine: 'Api, emoliente, jugos, pan con chicharrón', address: 'Perímetro de la Plaza de Armas', zone: 'Centro / Plaza de Armas', segment: 'Económico', cartas: 'Jugos y desayuno rápido', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Punto de levantamiento: censar carretillas de 05:00 a 09:00' },
  { name: 'Carretillas Mercado Central', localType: 'Carretilla / ambulante', cuisine: 'Api, jugos, panes', address: 'Alrededor del Mercado Central', zone: 'Mercado Central / Jr. Oquendo', segment: 'Económico', cartas: 'Jugos y desayuno rápido', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Punto de levantamiento de madrugada' },
  { name: 'Carretillas Terminal Terrestre', localType: 'Carretilla / ambulante', cuisine: 'Jugos, sándwiches, emoliente', address: 'Terminal Terrestre de Puno', zone: 'Av. Simón Bolívar', segment: 'Económico', cartas: 'Jugos y desayuno rápido', dailyMenu: '', menuPrice: '', cartaRange: '', phone: '', schedule: '', ownDelivery: '', platform: '', priority: '', source: 'Tráfico de pasajeros a toda hora — verificar en campo' },
];

export const restaurantZones = ['Av. Circunvalación', 'Av. El Sol', 'Av. La Torre', 'Av. Sesquicentenario', 'Av. Simón Bolívar', 'Barrio Bellavista', 'Centro / Plaza de Armas', 'Mercado Central / Jr. Oquendo', 'Por confirmar', 'Puerto / Uros'];
export const restaurantTypes = ['Broastería / salchipapería', 'Cafetería', 'Carretilla / ambulante', 'Cevichería', 'Chifa', 'Japonés / fusión', 'Menú popular', 'Parrilla', 'Pizzería', 'Pollería', 'Puesto de mercado', 'Restaurante turístico', 'Vegetariano / vegano'];
export const restaurantSegments = ['Económico', 'Estándar', 'Medio', 'Premium'];
export const restaurantCartas = ['Almuerzos', 'Cenas', 'Desayunos', 'Especiales', 'Jugos y aperitivos', 'Jugos y desayuno rápido'];
